name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  

      - name: Copy files to gh-pages temp directory
        run: |
          set -e

          mkdir -p gh-pages-temp
          cp -r public/* gh-pages-temp/

          mkdir -p gh-pages-temp/js
          cp src/converter.js gh-pages-temp/js/
          cp src/maskedInputController.js gh-pages-temp/js/
          cp src/userSettingsController.js gh-pages-temp/js/

      - name: Commit & push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages-temp
          publish_branch: gh-pages